apiVersion: v1
kind: Pod
metadata:
  name: client
spec:
  containers:
    - image: localhost:5000/smundada/oidc-adventures/client-58bf3581096f28f603bcda285193bbb5:v1.1@sha256:9cd18d78ab04d889a8f77b95bc22c2c542ea003022fab86f0154f7e94be37acb
      name: client
      volumeMounts:
        - mountPath: /var/run/secrets/tokens
          name: oidc-token
      env:
        - name: OIDC_TOKEN_PATH
          value: /var/run/secrets/tokens/oidc-token
        - name: OIDC_REQUIRED_SERVER
          value: http://server.default:80
      imagePullPolicy: IfNotPresent              
  volumes:
    - name: oidc-token
      projected:
        sources:
          - serviceAccountToken:
              path: oidc-token
              expirationSeconds: 600
              audience: adventures