apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app: server
spec:
  containers:
    - image: localhost:5000/oidc-adventures/server-6818c51d323208aeb565d2018dce3afa:v2@sha256:3ccf42ac8af2d5b1ae8c3eeffc61a7d35aee3f4e6ef7c903d7bbfe4886351059
      name: server
      env:
        - name: ISSUER_URL
          value: https://kubernetes.default.svc:443
        - name: OIDC_INTENDED_AUDIENCE
          value: adventures
      ports:
        - name: http
          containerPort: 8080
      imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080